using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using AtomicSplines
using LinearAlgebra
using Printf
using JLD2

function solve_carbon_rohf(R_max; verbose::Bool=true)
    println("=== Carbon ROHF Configuration Average (Z=6) ===")
    
    N_elems = 100
    Z = 6.0

    ws = cached_init_scf_workspace(R_max, N_elems, Val(7), Z; γ=2.5)

    basis = ws.basis

    n = basis.num_splines
    active_s = 2:(n-1)  
    active_p = 3:(n-1)  


    # 1s^2, 2s^2, 2p^2
    orbitals = [
        Orbital(1, 0, 2.0), # 1s (Closed)
        Orbital(2, 0, 2.0), # 2s (Closed)
        Orbital(2, 1, 2.0)  # 2p (Open, fractional w=2)
    ]
    
    H_core_s = ws.T + ws.V
    H_core_p = ws.T + ws.V + ws.R_inv2 
    
    # --- Initial Guess ---
    evals_s, evecs_s = eigen(Symmetric(H_core_s[active_s, active_s]), ws.S[active_s, active_s])
    orbitals[1].coeffs = zeros(Float64, n); orbitals[1].coeffs[active_s] = evecs_s[:, 1]
    orbitals[2].coeffs = zeros(Float64, n); orbitals[2].coeffs[active_s] = evecs_s[:, 2]
    
    evals_p, evecs_p = eigen(Symmetric(H_core_p[active_p, active_p]), ws.S[active_p, active_p])
    orbitals[3].coeffs = zeros(Float64, n); orbitals[3].coeffs[active_p] = evecs_p[:, 1]
    
    for orb in orbitals
        orb.coeffs ./= sqrt(dot(orb.coeffs, ws.S * orb.coeffs))
    end

    # Pre-allocate specific temporary matrices to avoid overwriting the global workspace
    J_core         = zeros(Float64, n, n)
    K_core_s       = zeros(Float64, n, n)
    K_core_p       = zeros(Float64, n, n)
    
    J_2p_spherical = zeros(Float64, n, n)
    K_2p_on_s      = zeros(Float64, n, n)
    
    J_2p_intra     = zeros(Float64, n, n)
    K_2p_intra     = zeros(Float64, n, n)

    E_old = 0.0
    MIXING = 0.0
    
    println("Comenzando ciclo SCF ROHF...")
    if verbose
        @printf("%-4s | %-14s | %-10s | %-8s\n", "Iter", "E_total (Ha)", "Delta E", "Time (s)")
        println("-"^78)
    end

    for iter in 1:100
        t0 = time()

        # ==========================================
        # PHASE 1: The Closed Core (1s + 2s)
        # ==========================================
        core_orbs = [orbitals[1], orbitals[2]]
        
        # Universal J matrix generated by the 4 core electrons
        build_total_J_matrix!(ws, core_orbs)
        J_core .= ws.J
        
        # Universal K matrices generated by the core, evaluated for s and p target spaces
        assemble_K_matrix!(ws, ws.K_mats[0], 0, core_orbs)
        K_core_s .= ws.K_mats[0]
        
        assemble_K_matrix!(ws, ws.K_mats[1], 1, core_orbs)
        K_core_p .= ws.K_mats[1]

        # ==========================================
        # PHASE 2: The Open 2p Shell Contributions
        # ==========================================
        
        # A. What the s-block feels from the 2p shell:
        # The s-electrons feel the full spherical average of all w=2.0 electrons in the 2p shell.
        build_specific_J_matrix!(ws, J_2p_spherical, orbitals[3], 2.0)
        assemble_K_matrix!(ws, ws.K_mats[0], 0, [orbitals[3]]) 
        K_2p_on_s .= ws.K_mats[0]

        # B. What the 2p electron feels from its own shell (Cowan's w-1 exact physics):
        # The 2p electron only feels w-1 = 1.0 other equivalent electron (Monopole F^0)
        build_specific_J_matrix!(ws, J_2p_intra, orbitals[3], 1.0)
        
        # The 2p electron experiences the specific quadrupole exchange (k=2, Coeff = 2/25)
        build_specific_K_matrix!(ws, K_2p_intra, orbitals[3], 2, 5.0 / 25.0)

        # ==========================================
        # PHASE 3: Assemble Shell-Dependent Fock Matrices
        # ==========================================
        
        F_s = ws.F_mats[0]
        F_p = ws.F_mats[1]
        
        # Unified s-block Operator: Core + 2p_spherical
        F_s .= H_core_s .+ J_core .+ J_2p_spherical .- K_core_s .- K_2p_on_s
        
        # Specific 2p Operator: Core + 2p_intra
        F_p .= H_core_p .+ J_core .+ J_2p_intra .- K_core_p .- K_2p_intra
        
        # ==========================================
        # PHASE 4: Diagonalization & Orthogonalization
        # ==========================================
        
        # Because 1s and 2s share F_s, diagonalizing it yields strictly orthogonal s-states!
        evals_fs, evecs_fs = eigen(Symmetric(F_s[active_s, active_s]), ws.S[active_s, active_s])
        
        # The 2p block is diagonalized independently (orthogonal to s by spherical harmonics)
        evals_fp, evecs_fp = eigen(Symmetric(F_p[active_p, active_p]), ws.S[active_p, active_p])
        
        # --- Update Orbitals (With Linear Mixing) ---
        c_1s_new = zeros(Float64, n); c_1s_new[active_s] = evecs_fs[:, 1]
        c_1s_new ./= sqrt(dot(c_1s_new, ws.S * c_1s_new))
        orbitals[1].coeffs = MIXING * orbitals[1].coeffs + (1 - MIXING) * c_1s_new
        orbitals[1].coeffs ./= sqrt(dot(orbitals[1].coeffs, ws.S * orbitals[1].coeffs))
        orbitals[1].energy = evals_fs[1]

        c_2s_new = zeros(Float64, n); c_2s_new[active_s] = evecs_fs[:, 2]
        c_2s_new ./= sqrt(dot(c_2s_new, ws.S * c_2s_new))
        orbitals[2].coeffs = MIXING * orbitals[2].coeffs + (1 - MIXING) * c_2s_new
        orbitals[2].coeffs ./= sqrt(dot(orbitals[2].coeffs, ws.S * orbitals[2].coeffs))
        orbitals[2].energy = evals_fs[2]

        c_2p_new = zeros(Float64, n); c_2p_new[active_p] = evecs_fp[:, 1]
        c_2p_new ./= sqrt(dot(c_2p_new, ws.S * c_2p_new))
        orbitals[3].coeffs = MIXING * orbitals[3].coeffs + (1 - MIXING) * c_2p_new
        orbitals[3].coeffs ./= sqrt(dot(orbitals[3].coeffs, ws.S * orbitals[3].coeffs))
        orbitals[3].energy = evals_fp[1]
 
        # ==========================================
        # PHASE 5: Compute True Configuration Average Energy
        # ==========================================
        E_total = 0.0

        h_11 = dot(orbitals[1].coeffs, H_core_s * orbitals[1].coeffs)
        E_total += (orbitals[1].occ / 2.0) * (h_11 + orbitals[1].energy)
        
        h_22 = dot(orbitals[2].coeffs, H_core_s * orbitals[2].coeffs)
        E_total += (orbitals[2].occ / 2.0) * (h_22 + orbitals[2].energy)
        
        h_pp = dot(orbitals[3].coeffs, H_core_p * orbitals[3].coeffs)
        E_total += (orbitals[3].occ / 2.0) * (h_pp + orbitals[3].energy)
        
        delta = abs(E_total - E_old)
        elapsed = time() - t0
        
        if verbose
            @printf("%-4d | %14.8f | %10.2e | %8.4f\n", iter, E_total, delta, elapsed)
        end
        
        if delta < 1e-9
            if verbose 
                println("-"^78)
                println("Converged in $iter iterations.")
            end
            @printf("Energía final HF-av: %.6f Ha\n", E_total)

            dense_grid = exp.(range(log(1e-8), log(R_max), length=10000))
            V_eff = compute_effective_central_potential(ws, orbitals, dense_grid, Z)
            P_2p = evaluate_orbital(ws.basis, orbitals[3].coeffs, dense_grid)

            filename = "carbon_rohf_results_R$(R_max).jld2"
            jldsave(filename;
                    orbitals = orbitals,
                    E_total = E_total,
                    R_max = R_max,
                    R_grid = dense_grid,
                    V_nuclear = ws.V,
                    V_eff = V_eff,
                    P_2p = P_2p,
                    num_splines = n,
                    active_s = active_s,
                    active_p = active_p
                    )
            println("Saved strictly optimized ROHF data to $filename")
            println("===== END =====")
            break
        end
        
        E_old = E_total
    end
end

solve_carbon_rohf(30.0)
